workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"  # Ajusta la ruta según tu estructura de proyecto
        XCODE_SCHEME: "App"  # Ajusta el nombre del esquema según tu configuración
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Angular project
        script: |
          npm run build
      - name: Copy web assets to iOS
        script: |
          npx cap copy ios
      - name: Sync Capacitor with iOS
        script: |
          npx cap sync ios
      - name: Build iOS
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $HOME/output/App.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/output/App.xcarchive -exportOptionsPlist ios/App/Info.plist -exportPath $HOME/output
    artifacts:
      - $HOME/output/*.ipa
