workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        # Asumimos que no necesitas las siguientes variables de firma
        # DEVELOPMENT_TEAM: "YOUR_TEAM_ID"
        # CODE_SIGN_IDENTITY: "Apple Development"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Angular project
        script: |
          npm run build --prod
      - name: Copy web assets to iOS
        script: |
          npx cap copy ios
      - name: Sync Capacitor with iOS
        script: |
          npx cap sync ios
      - name: Build iOS without signing
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release archive -archivePath $HOME/output/App.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Export IPA
        script: |
          cd $HOME/output
          xcodebuild -exportArchive -archivePath $HOME/output/App.xcarchive -exportOptionsPlist ios/App/App/Info.plist -exportPath .
          mv *.ipa App.ipa
    artifacts:
      - $HOME/output/App.ipa